name: big_date
description: A Dart library that expand DateTime, it also support diiferent countries` calendar.
version: 0.2.2
homepage: https://github.com/normidar/big_date

environment:
  sdk: '>=2.16.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.0
  auto_exporter: ^1.4.1
  lints: ^1.0.0
  test: ^1.16.0
